popular_domains = [
    "google.com", "youtube.com", "facebook.com", "baidu.com", "wikipedia.org",
    "qq.com", "taobao.com", "tmall.com", "amazon.com", "yahoo.com",
    "twitter.com", "instagram.com", "linkedin.com", "reddit.com", "netflix.com",
    "microsoft.com", "office.com", "apple.com", "live.com", "bing.com",
    "vk.com", "zoom.us", "pinterest.com", "tumblr.com", "ebay.com",
    "twitch.tv", "aliexpress.com", "paypal.com", "wordpress.com", "msn.com",
    "stackoverflow.com", "github.com", "adobe.com", "whatsapp.com", "telegram.org",
    "discord.com", "slack.com", "dropbox.com", "medium.com", "quora.com",
    "imgur.com", "soundcloud.com", "spotify.com", "archive.org", "bbc.com",
    "cnn.com", "nytimes.com", "walmart.com", "target.com", "bestbuy.com",
    "hulu.com", "espn.com", "weather.com", "craigslist.org", "etsy.com",
    "aliexpress.ru", "dzen.ru", "ok.ru", "tiktok.com", "weibo.com",
    "jd.com", "sina.com.cn", "sohu.com", "naver.com", "daum.net",
    "rakuten.co.jp", "amazon.co.jp", "amazon.de", "amazon.co.uk", "amazon.in",
    "booking.com", "airbnb.com", "tripadvisor.com", "expedia.com", "zillow.com",
    "indeed.com", "glassdoor.com", "udemy.com", "coursera.org", "edx.org",
    "khanacademy.org", "duolingo.com", "deviantart.com", "flickr.com", "pixiv.net",
    "wix.com", "shopify.com", "wordpress.org", "blogger.com", "medium.com",
    "patreon.com", "substack.com", "notion.so", "trello.com", "asana.com",
    "atlassian.com", "gitlab.com", "bitbucket.org", "docker.com", "kubernetes.io",
    "nginx.org", "apache.org", "mysql.com", "postgresql.org", "mongodb.com",
    "redis.io", "elastic.co", "grafana.com", "prometheus.io", "jenkins.io"
]